FROM node:10
## WORKDIR specifies the directory our
## application's code will live within
WORKDIR /app
## We copy our package.json file to our
## app directory
COPY package.json /app
## We then run npm install to install
## express for our application
RUN npm install
## We then copy the rest of our application
## to the app direcoty
COPY . /app
RUN node generateKeypair.js

## We start our application by calling
## npm start.
EXPOSE 8080
CMD ["npm", "run", "start"]