module.exports = {
  customers: "customers",
  dressings: "dressings",
  looks: "looks",
  products: "products",
  productItems: "productItems",
  categories: "categories",
  users: "users",
  placeholders: "placeholders",
  disponibilites: "disponibilites",
  periodes: "periodes",
  sujets: "sujets",
  periode_disponibilites: "periode_disponibilites",
  seances: "seances",
  consultations: "consultations",
  experts: "experts",
};
